[package]
name = "cch23-fargito"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
serde = "1.0.193"
serde_json = "1.0.108"
shuttle-axum = "0.35.1"
shuttle-runtime = "0.35.2"
tokio = "1.35.1"
tracing = "0.1.40"
